services:
  web:
    build: ./frontend
    # environment:
    #   CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:5173"  
    volumes:
      - ./frontend:/app  
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge