services:
  # web:
  #   build: ./frontend
  #   # environment:
  #   #   CHOKIDAR_USEPOLLING: "true"
  #   ports:
  #     - "3000:5173"  
  #   volumes:
  #     - ./frontend:/app  
  #     - /app/node_modules

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app_network
  db:
      image: postgres:17 
      restart: always
      environment:
        POSTGRES_USER: myuser         
        POSTGRES_PASSWORD: mypassword 
        POSTGRES_DB: mydatabase       
      ports:
        - "5432:5432"  
      volumes:
        - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge